version: '3.4'

services:
  tinyurldb:
    container_name: tinyurldb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  tinyurl:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro